Added User/Pass Authentication to Sock5 Dialer and Config
Jigsaw-Code/outline-sdk pull request #184
Opened 2024-02-20 16:55 UTC by amircybersec

This PR adds username/password authentication to Socks5 dialer and config package. The config URL for socks5 with authentication looks like this:

```
socks5://username:password@hostname:port
```

For testing I am currently using using [this](https://github.com/armon/go-socks5) socks5 server implementation. 

TODO
- [ ] Add tests for authentication

2024-02-22 20:12 UTC, amircybersec commented
@fortuna I managed to get socks5 working with single round trip for both no-auth and auth. I pushed the code to the PR however the build is failing with this error: 

`Error: config/socks5.go:27:17: undefined: socks5.Credentials`

I believe the build process is looking at current sock5 implementation in transport package which does not have `Credentials` defined and this change is made in the PR...Do you have any idea how to fix this issue in the build check?

The code is running fine locally and I have added end-to-end tests for using a go server implementation I found.

2024-02-22 21:57 UTC, fortuna requested changes

2024-02-22 21:57 UTC, fortuna commented on transport/socks5/stream_dialer.go
> +	var buffer []byte
We were pre-allocating before to avoid multiple allocations. Please keep doing the same.

2024-02-22 21:57 UTC, fortuna commented on transport/socks5/stream_dialer.go
> +type Credentials struct {
Please reference https://datatracker.ietf.org/doc/html/rfc1929

2024-02-22 21:57 UTC, fortuna commented on transport/socks5/stream_dialer.go
> +	Username string
According to the RFC, these should be []byte

2024-02-22 21:57 UTC, fortuna commented on transport/socks5/stream_dialer.go
> +func NewStreamDialer(endpoint transport.StreamEndpoint, cred Credentials) (transport.StreamDialer, error) {
Credentials should be a pointer, so we can pass nil.

You must check the length of the credentials, which must be <=255

2024-02-25 21:25 UTC, amircybersec commented
This PR is now replaced with a new PR https://github.com/Jigsaw-Code/outline-sdk/pull/189.

2024-02-25 21:25 UTC, closed without merging

2024-02-25 21:26 UTC, amircybersec commented
@fortuna your feedback on this PR is applied to the new PR https://github.com/Jigsaw-Code/outline-sdk/pull/189.