fix: address race condition in socks5 test
Jigsaw-Code/outline-sdk pull request #278
Opened 2024-09-06 19:48 UTC by amircybersec

This PR attempts to resolve issue https://github.com/Jigsaw-Code/outline-sdk/issues/276

2024-09-09 16:02 UTC, fortuna commented on transport/socks5/stream_dialer_test.go
> -		t.Log("server is listening...")
What's the race condition? This doesn't seem like it makes any difference.

2024-09-11 04:06 UTC, amircybersec commented
@fortuna I added sync.WaitGroup to wait for go routines to complete.

2024-09-11 19:10 UTC, fortuna requested changes

2024-09-11 19:10 UTC, fortuna commented on transport/socks5/stream_dialer_test.go
> +	//defer listener.Close()
```suggestion
```

2024-09-11 19:10 UTC, fortuna commented on transport/socks5/stream_dialer_test.go
> +	var running sync.WaitGroup
Move this to just before the `go func()`, so it's clearer you are adding that goroutine

2024-09-11 19:10 UTC, fortuna commented on transport/socks5/stream_dialer_test.go
> +	listener.Close()
I believe this won't close if the test fails earlier. Instead, defer a function that does both the close and wait.

2024-09-11 19:10 UTC, fortuna commented on transport/socks5/stream_dialer_test.go
> +	var running sync.WaitGroup
Same comments

2024-09-11 22:26 UTC, amircybersec commented
@fortuna thanks for the feedback. I made the changes accordingly.

2024-09-11 22:26 UTC, fortuna approved these changes

2024-09-11 22:27 UTC, merged

2024-09-11 22:27 UTC, fortuna commented
Thanks for the fix!